### ISSUE TITLE
f5_network_connectivity_checks: Question

### ISSUE THREAD

**Issue by lisonlp** [f5devcentral/f5-big-iq-pm-team#10]
### BIG-IQ version 8.2.0.1, 2* BIG-IQ CMs and 6*BIG-IQ DCDs

At the question: **BIG-IQ DCD Discovery/Listener IP address(es)?**
What do you mean? Should we enter the Discovery AND Listener IP of each DCD?

At the question: **BIG-IQ DCD Data Collection IP address(es)?**
What IP are you referring to? there are only 4 possible IPs: Mgmt, Discovery, Listener and Cluster.

**Comment by rjouhann** [comment]
>  At the question: BIG-IQ DCD Discovery/Listener IP address(es)?
> What do you mean? Should we enter the Discovery AND Listener IP of each DCD?

You can enter either the Discovery IP OR the listener IP of each DCD.

> At the question: BIG-IQ DCD Data Collection IP address(es)?
> What IP are you referring to? there are only 4 possible IPs: Mgmt, Discovery, Listener and Cluster.

Management IP

**Comment by lisonlp** [comment]
Thanks a lot for the answers @rjouhann!
