### ISSUE TITLE
remove currentRPM from the upgrade cmd

### ISSUE THREAD

**Issue by gwolfis** [f5devcentral/f5-big-iq-pm-team#6]
Just used the script and it works great.

The only confusing part was actually in the README.

When upgrading BIG-IQ with the new AS3 package the description says "./as3_rpm_update_bigiq.sh <newRPM> <currentRPM>"

My experience is that only defining the newRPM is enough to be successful. Can you please update and remove the <currentRPM>

btw. just using the script ./as3_rpm_update_bigiq.sh returns an explanation how to use the script. I like that.

**Comment by rjouhann** [comment]
done
