### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by tjvreugdenhil** [f5devcentral/f5-big-iq-pm-team#7]
I cannot get script to run: 

root@(BIG_IQ_CM)(cfg-sync Standalone)(Active)(/Common)(tmos)# show sys version

Sys::Version
Main Package
  Product     BIG-IQ
  Version     8.1.0.1
  Build       0.0.30
  Edition     Point Release 1
  Date        Fri Aug  6 09:51:34 PDT 2021
[root@BIG_IQ_CM:Active:Standalone] scripts # ls -al
total 24
drwxr-xr-x.  2 root root  4096 Sep 16 07:54 .
drwxr-xr-x. 31 root root  4096 Sep 16 07:32 ..
-rwxr-xr-x.  1 root root 15390 Sep 16 07:51 f5_network_connectivity_checks.sh
[root@BIG_IQ_CM:Active:Standalone] scripts # pwd
/shared/scripts
[root@BIG_IQ_CM:Active:Standalone] scripts # bash
[root@BIG_IQ_CM:Active:Standalone] scripts #  ./f5_network_connectivity_checks.sh 
: No such file or directory

**Comment by rjouhann** [comment]
Hello @tjvreugdenhil,

1. Have you run "`chmod +x f5_network_connectivity_checks.sh`"? 
2. How did you upload the script in the system?
3. Could you run `ls -lrth /shared/scripts/f5_network_connectivity_checks.sh`?

Thanks & Regards,
Roman

**Comment by tjvreugdenhil** [comment]
Hi @rjouhann  - 
1) yep, that worked. 
2) I had to copy the contents of the script to a file, and WinSCP this file to /shared/scripts because we don't yet have internet access to poll from github. 
3) [root@BIG_IQ_CM:Active:Standalone] config # ls -lrth /shared/scripts/f5_network_connectivity_checks.sh
-rwxr-xr-x. 1 root root 16K Sep 16 07:51 /shared/scripts/f5_network_connectivity_checks.sh

**Comment by rjouhann** [comment]
Hello,

I am thinking something went wrong when copy the contents of the script into a file as you are on windows.

Could you try to use the tool dos2unix (https://www.fileformat.info/convert/text/dos2unix.tr) and re-upload the script?

Thanks & Regards,
Roman

**Comment by tjvreugdenhil** [comment]
I copied and pasted from github into vi, insert mode, and CTRL + SHIFT + V and I was able to start the script. 
Thanks!

**Comment by rjouhann** [comment]
Thanks for the update, glad you made it work!
